services:
  reports_db:
    image: postgres:16
    container_name: reports_db
    networks:
      - cloudbuild
    ports:
      - "5433:5432"
    env_file:
      - ./.env
    volumes:
      - reports_db:/var/lib/postgresql/data
      
  reports_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reports_app
    networks:
      - cloudbuild
    depends_on:
      - reports_db
    env_file:
      - ./.env
    
volumes:
  reports_db:
  
  
networks:
  cloudbuild:
    external: true
