version: "3"
networks:
    openhim:
    hapi-fhir:
    mediators:
    cloudbuild: 
        external: true


services:
    mongo:
        container_name: openhim-mongo
        image: mongo:4.0
        networks:
            - openhim
        volumes:
            - mongodb-data:/data/db
        restart: unless-stopped

    hapi-fhir-postgres:
        container_name: hapi-fhir-postgres
        image: postgres:14-alpine
        restart: always
        networks:
            - hapi-fhir
            - cloudbuild
        environment:
            POSTGRES_USER: postgres
            POSTGRES_DB: hapi
            POSTGRES_PASSWORD: hapi123
        volumes:
            - 'hapi-fhir-postgres:/var/lib/postgresql/data'

    hapi-fhir-jpa:
        image: hapiproject/hapi:latest
        container_name: hapi-fhir-jpa
        restart: unless-stopped
        networks:
            - hapi-fhir
            - cloudbuild
        depends_on:
            - hapi-fhir-postgres
        ports:
            - "8888:8080"
        volumes:
            - "./hapi-fhir:/hapi"
        environment:
            SPRING_CONFIG_LOCATION: /hapi/application.yaml

    openhim-core:
        container_name: openhim-core
        restart: unless-stopped
        image: jembi/openhim-core:latest
        environment:
            - mongo_url=mongodb://mongo/openhim
            - mongo_atnaUrl=mongodb://mongo/openhim
            - authentication_enableJWTAuthentication=true
        ports:
            - "8080:8080"
            # - "5000:5000"
            - "5001:5001"
            # - "5050:5050"
            # - "5051:5051"
            # - "5052:5052"
            # - "7788:7788"
        depends_on:
            - mongo
        networks:
            - openhim
            - hapi-fhir
            - mediators
        healthcheck:
            test: "curl -sSk https://openhim-core:8080/heartbeat || exit 1"
            interval: 30s
            timeout: 30s
            retries: 3

    openhim-console:
        container_name: openhim-console
        image: jembi/openhim-console:latest
        restart: unless-stopped
        networks:
            - openhim
        healthcheck:
            test: "curl -sS http://openhim-console || exit 1"
            interval: 30s
            timeout: 30s
            retries: 3
        volumes:
            - ./default.json:/usr/share/nginx/html/config/default.json:ro
            - /etc/ssl/crt:/etc/nginx/certs

    mediators:
        depends_on:
            - openhim-core
        container_name: mediators
        build: mediators
        restart: unless-stopped
        networks:
            - openhim
            - hapi-fhir
        # ports:
        #     - "8082:3000"
        env_file:
            - mediators/.env
    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        networks:
            - openhim
            - hapi-fhir
            - cloudbuild
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./../nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - openhim-core

volumes:
    mongodb-data:
    hapi-fhir-postgres:
    hapi:
