version: '3'

volumes:
  keycloak-postgres:
      driver: local

networks:
  cloudbuild:
    external: true

services:
  keycloak-postgres:
      image: postgres:14-alpine
      restart: always
      networks:
            - cloudbuild
      environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: keycloak
          POSTGRES_PASSWORD: keycloak_not_123
      volumes:
        - 'keycloak-postgres:/var/lib/postgresql/data'

  keycloak:
      image: quay.io/keycloak/keycloak:latest
      networks:
        - cloudbuild
      env_file:
        - ../keycloak/.env
      depends_on:
        - keycloak-postgres
      command: start-dev
      
  # smart-config:
  #   image: alvearie/keycloak-config
  #   networks: 
  #   - cloudbuild
  #   depends_on:
  #     keycloak:
  #       condition: service_healthy
  #   environment:
  #   - KEYCLOAK_BASE_URL=http://keycloak:8080/auth
  #   - KEYCLOAK_USER
  #   - KEYCLOAK_PASSWORD
  #   - KEYCLOAK_REALM=${SMART_REALM:-dummy-smart}

  # proxy-config:
  #   image: us-docker.pkg.dev/fhir-proxy-build/stable/keycloak-config:latest
  #   networks: 
  #   - cloudbuild
  #   depends_on:
  #     smart-config:
  #       condition: service_completed_successfully
  #   environment:
  #   - KEYCLOAK_BASE_URL=http://keycloak:8080/auth
  #   - KEYCLOAK_USER
  #   - KEYCLOAK_PASSWORD
  #   - TEST_REALM
  #   - TEST_USER
  #   - TEST_PASS
  #   - SMART_REALM

